apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  database_url: "postgresql://postgres:postgres@postgres:5432/postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  API_URL: "http://elixir-backend:4000"