name: TimeManager CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ELIXIR_VERSION: '1.14.x'
  OTP_VERSION: '25.x'
  NODE_VERSION: '20'

jobs:
  backend:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}
    
    - name: Cache Elixir deps
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: |
        cd time_manager
        mix deps.get

    - name: Setup database
      run: |
        cd time_manager
        mix ecto.create
        mix ecto.migrate
      env:
        MIX_ENV: dev
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/time_manager_dev

  frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install frontend dependencies
      run: |
        cd client
        npm install
    
    - name: Build frontend
      run: |
        cd client
        npm run build

  docker:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./time_manager/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-backend:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/timemanager-backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-frontend:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/timemanager-frontend:latest

    # Supprimez cette étape si vous n'avez pas de Dockerfile personnalisé pour la base de données
    # - name: Build and push database Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./bdd
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-db:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/timemanager-db:latest

    - name: Build and push pgAdmin Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./pgadmin/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/timemanager-pgadmin:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/timemanager-pgadmin:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    
    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i 's|image: .*backend:.*|image: '"${DOCKER_USERNAME}"'/timemanager-backend:'"${DOCKER_IMAGE_TAG}"'|' k8s/deployment.yaml
        sed -i 's|image: .*frontend:.*|image: '"${DOCKER_USERNAME}"'/timemanager-frontend:'"${DOCKER_IMAGE_TAG}"'|' k8s/deployment.yaml
        sed -i 's|image: .*db:.*|image: '"${DOCKER_USERNAME}"'/timemanager-db:'"${DOCKER_IMAGE_TAG}"'|' k8s/deployment.yaml
        sed -i 's|image: .*pgadmin:.*|image: '"${DOCKER_USERNAME}"'/timemanager-pgadmin:'"${DOCKER_IMAGE_TAG}"'|' k8s/deployment.yaml
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    - name: Run database migrations
      run: |
        kubectl exec -it deployment/time-manager-backend -- /app/bin/time_manager eval "TimeManager.Release.migrate()"
      env:
        MIX_ENV: prod

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/time-manager-backend
        kubectl rollout status deployment/time-manager-frontend
        kubectl rollout status deployment/postgres-db
        kubectl rollout status deployment/pgadmin